name: build game
on: [push, pull_request]

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      IOS_BUILD_ONLY: yup # Just run a build check
      IOS_TEAM: dummy
      IOS_SIGN_ID: "dummy Certificate Name"
      IOS_BUNDLE_ID: com.github.m4c0.example
      IOS_PROV_PROF: "dummy Development"
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - run: brew install glslang spirv-cross
      - run: curl -L -o moltenvk.tar https://github.com/KhronosGroup/MoltenVK/releases/download/v1.4.2/MoltenVK-ios.tar
      - run: tar xfv moltenvk.tar
      - run: mv MoltenVK/MoltenVK/static/MoltenVK.xcframework/ .
      - run: clang -o build build-ios.c
      - run: ./build
  build-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - run: brew install glslang spirv-cross
      - run: curl -L -o moltenvk.tar https://github.com/KhronosGroup/MoltenVK/releases/download/v1.4.2/MoltenVK-macos.tar
      - run: tar xfv moltenvk.tar
      - run: mv MoltenVK/MoltenVK/static/MoltenVK.xcframework/ .
      - run: touch libvulkan.dylib # hack
      - run: clang -o build build-osx.c
      - run: ./build
  build-windows:
    runs-on: windows-latest
    steps:
      - run: dir 'c:\Program Files (x86)\Windows Kits\10\bin'
      - run: vcpkg install spirv-cross
      - uses: actions/checkout@v6
        with:
          submodules: true
      - run: curl -L -o glslang.zip https://github.com/KhronosGroup/glslang/releases/download/main-tot/glslang-main-windows-x86_64-release.zip
      - run: unzip glslang.zip bin/glslang.exe
      - run: mv bin/glslang.exe .
      - run: copy "C:\vcpkg\installed\x64-windows\tools\spirv-cross\spirv-cross.exe" .
      - run: clang -o build.exe build-win.c
      - run: ./build.exe
        env:
          WIN_KIT_VERSION: 10.0.26100.0
          WIN_IDENTITY_NAME: ${{ secrets.WIN_IDENTITY_NAME }}
          WIN_IDENTITY_PUBLISHER: ${{ secrets.WIN_IDENTITY_PUBLISHER }}
      - uses: actions/upload-artifact@v7
        with:
          name: windows-exe
          path: sokoban.exe
      - uses: actions/upload-artifact@v7
        with:
          name: windows-msix
          path: sokoban.msix


